#!/bin/bash
# Unwetter4Lox postroot.sh
# Wird mit Root-Rechten nach der Installation aufgerufen

PLUGIN="unwetter4lox"

# LBHOMEDIR ermitteln - mehrere Methoden als Fallback
if [ -z "$LBHOMEDIR" ]; then
    # Methode 1: aus /etc/environment parsen
    LBHOMEDIR=$(grep "^LBHOMEDIR=" /etc/environment 2>/dev/null | head -1 | cut -d= -f2 | tr -d '"' | tr -d "'")
fi
if [ -z "$LBHOMEDIR" ]; then
    # Methode 2: source /etc/environment
    set -a; source /etc/environment 2>/dev/null; set +a
fi
if [ -z "$LBHOMEDIR" ]; then
    # Methode 3: Standard LoxBerry Pfad
    LBHOMEDIR="/opt/loxber""ry"  # Standard LoxBerry Pfad als letzter Fallback
fi

echo "<INFO> LBHOMEDIR=${LBHOMEDIR}"
echo "<INFO> PLUGIN=${PLUGIN}"

DAEMON="${LBHOMEDIR}/system/daemons/plugins/${PLUGIN}"
SUDOERS="/etc/sudoers.d/${PLUGIN}"
LOGDIR="${LBHOMEDIR}/log/plugins/${PLUGIN}"

# Log-Verzeichnis anlegen
mkdir -p "${LOGDIR}"
chown loxberry:loxberry "${LOGDIR}" 2>/dev/null

# Sudoers-Datei erstellen
echo "<INFO> Erstelle sudoers: ${SUDOERS}"
{
    echo "# Unwetter4Lox - generated by postroot.sh"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s\n' "${DAEMON}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s start\n' "${DAEMON}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s stop\n' "${DAEMON}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s restart\n' "${DAEMON}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s status\n' "${DAEMON}"
} > "${SUDOERS}"

chmod 0440 "${SUDOERS}"
chown root:root "${SUDOERS}"

echo "<INFO> Sudoers Inhalt:"
cat "${SUDOERS}"

# Syntax prüfen
if visudo -c -f "${SUDOERS}" >/dev/null 2>&1; then
    echo "<OK> sudoers Syntax OK"
else
    echo "<ERR> sudoers Syntax-Fehler! Entferne Datei."
    cat "${SUDOERS}" >&2
    rm -f "${SUDOERS}"
    exit 1
fi

# Config-Handling: Upgrade-Backup wiederherstellen ODER Default anlegen
# Backup liegt in /tmp/ weil LoxBerry den config/-Ordner beim Update komplett löscht.
CFGDIR="${LBHOMEDIR}/config/plugins/${PLUGIN}"
CFGFILE="${CFGDIR}/${PLUGIN}.cfg"
CFGDEF="${CFGDIR}/${PLUGIN}.cfg.default"
CFGBAK_TMP="/tmp/${PLUGIN}_cfg_upgrade.bak"      # primärer Backup-Ort (überlebt Ordner-Löschung)
CFGBAK="${CFGDIR}/${PLUGIN}.cfg.upgrade_bak"      # legacy Fallback (ältere Versionen)

mkdir -p "${CFGDIR}"

if [ -f "${CFGBAK_TMP}" ]; then
    cp "${CFGBAK_TMP}" "${CFGFILE}"
    chown loxberry:loxberry "${CFGFILE}" 2>/dev/null
    rm -f "${CFGBAK_TMP}"
    echo "<OK> Konfiguration aus /tmp Backup wiederhergestellt: ${CFGFILE}"
elif [ -f "${CFGBAK}" ]; then
    mv "${CFGBAK}" "${CFGFILE}"
    chown loxberry:loxberry "${CFGFILE}" 2>/dev/null
    echo "<OK> Konfiguration aus Ordner-Backup wiederhergestellt: ${CFGFILE}"
elif [ -f "${CFGDEF}" ] && [ ! -f "${CFGFILE}" ]; then
    cp "${CFGDEF}" "${CFGFILE}"
    chown loxberry:loxberry "${CFGFILE}" 2>/dev/null
    echo "<OK> Standard-Config angelegt (Erstinstallation): ${CFGFILE}"
else
    echo "<INFO> Bestehende Config bleibt erhalten: ${CFGFILE}"
fi

# Neue Config-Sektionen ergänzen wenn noch nicht vorhanden (Upgrade-Migration)
if [ -f "${CFGFILE}" ] && ! grep -q "^\[TAWES\]" "${CFGFILE}"; then
    printf '\n[TAWES]\nENABLED=1\nMAX_DISTANCE_KM=120\n' >> "${CFGFILE}"
    echo "<OK> TAWES-Sektion zur Config hinzugefügt"
fi
if [ -f "${CFGFILE}" ] && ! grep -q "^REGEN_ALARM=" "${CFGFILE}"; then
    sed -i '/^\[THRESHOLDS\]/a REGEN_ALARM=10.0' "${CFGFILE}"
    echo "<OK> REGEN_ALARM zur Config hinzugefügt (Standard: 10.0 mm/h)"
fi

# Daemon-Script ausführbar machen (LoxBerry kopiert daemon/daemon nach system/daemons/plugins/)
DAEMONSCRIPT="${LBHOMEDIR}/system/daemons/plugins/${PLUGIN}"
if [ -f "${DAEMONSCRIPT}" ]; then
    chmod +x "${DAEMONSCRIPT}"
    echo "<OK> Daemon-Script chmod +x: ${DAEMONSCRIPT}"
else
    echo "<WARNING> Daemon-Script nicht gefunden: ${DAEMONSCRIPT}"
fi

# Python-Daemon ausführbar machen
PYDAEMON="${LBHOMEDIR}/bin/plugins/${PLUGIN}/unwetter4lox_daemon.py"
if [ -f "${PYDAEMON}" ]; then
    chmod +x "${PYDAEMON}"
    echo "<OK> Python-Daemon chmod +x: ${PYDAEMON}"
fi

# Daemon nach Installation/Update automatisch starten wenn Standort konfiguriert ist.
# Läuft hier aus postroot.sh (root) – kein sudo nötig, zuverlässiger als postinstall.sh.
# Bevorzugt su -s /bin/bash loxberry damit der Daemon als loxberry-User läuft;
# Fallback: direkte Ausführung als root (daemon.py funktioniert auch ohne LoxBerry SDK).
if [ -f "${DAEMONSCRIPT}" ] && [ -f "${CFGFILE}" ]; then
    LAT=$(grep "^LAT=" "${CFGFILE}" 2>/dev/null | cut -d= -f2 | tr -d ' \r')
    LON=$(grep "^LON=" "${CFGFILE}" 2>/dev/null | cut -d= -f2 | tr -d ' \r')
    if [ -n "$LAT" ] && [ -n "$LON" ]; then
        echo "<INFO> Standort konfiguriert (${LAT},${LON}) – starte Daemon nach Install/Update..."
        # runuser (Debian/Raspbian): kein Passwort nötig, speziell für root→user Transition
        if command -v runuser >/dev/null 2>&1; then
            runuser -s /bin/bash -c "\"${DAEMONSCRIPT}\" restart >/dev/null 2>&1" loxberry \
                && echo "<OK> Daemon als loxberry-User gestartet (runuser)" \
                || echo "<WARNING> runuser Daemon-Start fehlgeschlagen"
        elif su -s /bin/bash loxberry -c "\"${DAEMONSCRIPT}\" restart >/dev/null 2>&1" 2>/dev/null; then
            echo "<OK> Daemon als loxberry-User gestartet (su)"
        else
            echo "<INFO> su fehlgeschlagen, starte direkt als root..."
            "${DAEMONSCRIPT}" restart >/dev/null 2>&1 \
                && echo "<OK> Daemon als root gestartet" \
                || echo "<WARNING> Daemon-Start fehlgeschlagen – bitte manuell über Plugin-UI starten"
        fi
    else
        echo "<INFO> Kein Standort konfiguriert – Daemon wird nach Konfiguration gestartet"
    fi
else
    echo "<INFO> Daemon-Script oder Config noch nicht vorhanden – wird nach Konfiguration gestartet"
fi

# /etc/cron.d/ Eintrag: zuverlässiger als user-crontab, überlebt Updates
# @reboot:  startet Daemon 120s nach Systemstart (MQTT-Broker braucht Zeit)
# 0 3 *:    täglicher Neustart um 03:00 Uhr (bereinigt Langzeit-MQTT-Probleme)
# */5 *:    Watchdog – prüft ob Daemon noch läuft, bereinigt State bei Absturz
CROND="/etc/cron.d/${PLUGIN}"
PIDFILE="${LBHOMEDIR}/log/plugins/${PLUGIN}/daemon.pid"
STATEFILE="${LBHOMEDIR}/data/plugins/${PLUGIN}/state.json"
if [ -f "${DAEMONSCRIPT}" ]; then
    cat > "${CROND}" << CRONEOF
# Unwetter4Lox – Autostart + Watchdog + täglicher Restart
# Generiert von postroot.sh – nicht manuell bearbeiten
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

@reboot root sleep 120 && ${DAEMONSCRIPT} restart >/dev/null 2>&1
0 3 * * * root ${DAEMONSCRIPT} restart >/dev/null 2>&1
*/5 * * * * root if [ -f "${PIDFILE}" ] && ! kill -0 "\$(cat ${PIDFILE})" 2>/dev/null; then rm -f "${PIDFILE}" "${STATEFILE}"; ${DAEMONSCRIPT} start >/dev/null 2>&1; fi
CRONEOF
    chmod 0644 "${CROND}"
    chown root:root "${CROND}" 2>/dev/null
    echo "<OK> Cron-Jobs angelegt: ${CROND}"
    echo "<OK>   @reboot  – Autostart 120s nach Systemstart"
    echo "<OK>   03:00    – Täglicher Restart (bereinigt MQTT-Langzeitprobleme)"
    echo "<OK>   */5 min  – Watchdog: State löschen + Neustart bei Daemon-Absturz"
else
    echo "<WARNING> Daemon-Script nicht gefunden – Cron konnte nicht angelegt werden: ${DAEMONSCRIPT}"
fi

echo "<OK> postroot.sh abgeschlossen"
exit 0
