#!/bin/bash
# Unwetter4Lox postroot.sh
# Wird mit Root-Rechten nach der Installation aufgerufen

PLUGIN="unwetter4lox"

# LBHOMEDIR ermitteln - mehrere Methoden als Fallback
if [ -z "$LBHOMEDIR" ]; then
    # Methode 1: aus /etc/environment parsen
    LBHOMEDIR=$(grep "^LBHOMEDIR=" /etc/environment 2>/dev/null | head -1 | cut -d= -f2 | tr -d '"' | tr -d "'")
fi
if [ -z "$LBHOMEDIR" ]; then
    # Methode 2: source /etc/environment
    set -a; source /etc/environment 2>/dev/null; set +a
fi
if [ -z "$LBHOMEDIR" ]; then
    # Methode 3: Standard LoxBerry Pfad
    LBHOMEDIR="/opt/loxber""ry"  # Standard LoxBerry Pfad als letzter Fallback
fi

echo "<INFO> LBHOMEDIR=${LBHOMEDIR}"
echo "<INFO> PLUGIN=${PLUGIN}"

DAEMON="${LBHOMEDIR}/system/daemons/plugins/${PLUGIN}"
SUDOERS="/etc/sudoers.d/${PLUGIN}"
LOGDIR="${LBHOMEDIR}/log/plugins/${PLUGIN}"

# Log-Verzeichnis anlegen
mkdir -p "${LOGDIR}"
chown loxberry:loxberry "${LOGDIR}" 2>/dev/null

# Sudoers-Datei erstellen
echo "<INFO> Erstelle sudoers: ${SUDOERS}"
{
    echo "# Unwetter4Lox - generated by postroot.sh"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s\n' "${DAEMON}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s start\n' "${DAEMON}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s stop\n' "${DAEMON}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s restart\n' "${DAEMON}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s status\n' "${DAEMON}"
} > "${SUDOERS}"

chmod 0440 "${SUDOERS}"
chown root:root "${SUDOERS}"

echo "<INFO> Sudoers Inhalt:"
cat "${SUDOERS}"

# Syntax prüfen
if visudo -c -f "${SUDOERS}" >/dev/null 2>&1; then
    echo "<OK> sudoers Syntax OK"
else
    echo "<ERR> sudoers Syntax-Fehler! Entferne Datei."
    cat "${SUDOERS}" >&2
    rm -f "${SUDOERS}"
    exit 1
fi

# Config-Handling: Upgrade-Backup wiederherstellen ODER Default anlegen
CFGDIR="${LBHOMEDIR}/config/plugins/${PLUGIN}"
CFGFILE="${CFGDIR}/${PLUGIN}.cfg"
CFGDEF="${CFGDIR}/${PLUGIN}.cfg.default"
CFGBAK="${CFGDIR}/${PLUGIN}.cfg.upgrade_bak"

if [ -f "${CFGBAK}" ]; then
    mv "${CFGBAK}" "${CFGFILE}"
    chown loxberry:loxberry "${CFGFILE}"
    echo "<OK> Konfiguration aus Upgrade-Backup wiederhergestellt: ${CFGFILE}"
elif [ -f "${CFGDEF}" ] && [ ! -f "${CFGFILE}" ]; then
    cp "${CFGDEF}" "${CFGFILE}"
    chown loxberry:loxberry "${CFGFILE}"
    echo "<OK> Standard-Config angelegt: ${CFGFILE}"
else
    echo "<INFO> Bestehende Config bleibt erhalten: ${CFGFILE}"
fi

# Neue Config-Sektionen ergänzen wenn noch nicht vorhanden (Upgrade-Migration)
if [ -f "${CFGFILE}" ] && ! grep -q "^\[TAWES\]" "${CFGFILE}"; then
    printf '\n[TAWES]\nENABLED=1\nMAX_DISTANCE_KM=120\n' >> "${CFGFILE}"
    echo "<OK> TAWES-Sektion zur Config hinzugefügt"
fi
if [ -f "${CFGFILE}" ] && ! grep -q "^REGEN_ALARM=" "${CFGFILE}"; then
    sed -i '/^\[THRESHOLDS\]/a REGEN_ALARM=2.0' "${CFGFILE}"
    echo "<OK> REGEN_ALARM zur Config hinzugefügt"
fi

# Daemon-Script ausführbar machen (LoxBerry kopiert daemon/daemon nach system/daemons/plugins/)
DAEMONSCRIPT="${LBHOMEDIR}/system/daemons/plugins/${PLUGIN}"
if [ -f "${DAEMONSCRIPT}" ]; then
    chmod +x "${DAEMONSCRIPT}"
    echo "<OK> Daemon-Script chmod +x: ${DAEMONSCRIPT}"
else
    echo "<WARNING> Daemon-Script nicht gefunden: ${DAEMONSCRIPT}"
fi

# Python-Daemon ausführbar machen
PYDAEMON="${LBHOMEDIR}/bin/plugins/${PLUGIN}/unwetter4lox_daemon.py"
if [ -f "${PYDAEMON}" ]; then
    chmod +x "${PYDAEMON}"
    echo "<OK> Python-Daemon chmod +x: ${PYDAEMON}"
fi

echo "<OK> postroot.sh abgeschlossen"
exit 0
